modLoader = "javafml"
loaderVersion = "[2,)"
license = "MPLv2"
issueTrackerURL = "https://github.com/Cojomax99/JustEnoughDiscordIntegration/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Just Enough Discord Integration"
logoFile = "jedi.png"
credits = "Special thanks to my friends who wanted a Discord mod for our server. Also thanks tterrag and SuperCoder for helping get it off the ground!"
authors = "Cojomax99, Gegy"
description = '''
Connect your Minecraft chat with your Discord chat!
'''
